version: '3'
services:
  tomcat:
    image: tomcat:10.1.39-jdk17
    container_name: tomcat
    ports:
      - "8080:8080"
 #   volumes:
 #     - ./tomcat_data:/usr/local/tomcat
    restart: always
    networks:
      - tomcat-net
  
networks:
  tomcat-net:
    driver: bridge